// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hxmmpiwqidqgjsjzziyv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4bW1waXdxaWRxZ2pzanp6aXl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNDM3MjYsImV4cCI6MjA2NTcxOTcyNn0.iW-nf-gTSRb-86TXepL0WxN7qL8_HJFaovL5dgkNoIc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);